### PR TITLE
Home page Ready to get merge.

### PR DESCRIPTION
**Pull request by tigamadou**
I'm ready to merge the home page to the master branch. Thank you for your review.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by tigamadou** [comment]
New commit. I've done some changes.

**Comment by Anna-Myzukina** [comment]
#### Hi!
#### Wow, your project looks :+1: 
Few little Changes and your project will be perfect!


*** In original this part : ***
photo1

*** It`s in your version ***
photo

**** Signup button should be in the middle of screen ***

signup

*** Little troubles in footer with mobile version ***
screen

mob


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by tigamadou** [comment]
Errors checked.

**Review by Forison — COMMENTED** [review]
### Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi @genzaraki
Nice Job on implementing the changes suggested earlier, Here are a few changes we have to do to get this project approved.🙂

- [ ] Let us fix the errors and warnings returned by the HTML[ validator ](https://validator.w3.org)  after uploading ```index.html```🙂

> you have a tremendous😲 amount of styling even after using bootstrap🤔 , This is quite unusual per scope of this project🙂
> this could be replaced by ```.container .main-container``` by ```container-fluid``` of bootstrap🙂

## kindly make this change and submit the project for review
Feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.🙂
### Happy coding

**Comment by tigamadou** [comment]
@Forison  
All the checks have been done. But the main container class is to style the container with a given class. The result won't be the same if I use bootstrap's container-fluid, otherwise I'ld have to do more styling to get the result wanted. Please check again as there is no need of container-fluid here.

I'm submiting for a review. Thank you for your time.

**Review by imhta — APPROVED** [review]
# Project Approved 👏 
### @genzaraki Congratulations you have done a great job. Keep it up.  

#### Don't Forget to submit a project completion form
**Pon Muthu Selvam N**
Feel free contact me 
[Github //@imhta](https://github.com/imhta) | [Twitter //@nponmuthuselvam](https://twitter.com/ponmuthuselvam)

**Comment by tigamadou** [comment]
Thank you very much.

**Pull request merged**
